### ISSUE TITLE
Example create_voucher.php does not work

### ISSUE THREAD

**Issue by KarlBaumann** [Art-of-WiFi/UniFi-API-client#239]
The endpoint /api/login does not exist.
$controllerversion  = '8.5.6'; 

```
create_voucher.php
*   Trying 192.168.10.1:8443...
* Connected to 192.168.10.1 (192.168.10.1) port 8443
* ALPN: curl offers h2,http/1.1
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / x25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=tfm.bauman.is
*  start date: May 20 15:13:44 2023 GMT
*  expire date: Aug 18 15:13:43 2023 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
Host: 192.168.10.1:8443
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd

* Request completely sent off
< HTTP/1.1 404 
< Content-Length: 0
< Date: Fri, 11 Oct 2024 22:15:24 GMT
< 
* Connection #0 to host 192.168.10.1 left intact
* Found bundle for host: 0x600000092760 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection with host 192.168.10.1
> POST /api/login HTTP/1.1
Host: 192.168.10.1:8443
Accept-Encoding: deflate, gzip, br, zstd
Referer: https://192.168.10.1:8443/login
Accept: application/json
Content-Type: application/json
Content-Length: 44

* upload completely sent off: 44 bytes
< HTTP/1.1 404 
< Content-Length: 0
< Date: Fri, 11 Oct 2024 22:15:24 GMT
< 
* Connection #0 to host 192.168.10.1 left intact

<pre>
-----------LOGIN-------------
Array
(
    [url] => https://192.168.10.1:8443/api/login
    [content_type] => 
    [http_code] => 404
    [header_size] => 73
    [request_size] => 259
    [filetime] => -1
    [ssl_verify_result] => 20
    [redirect_count] => 0
    [total_time] => 0.004631
    [namelookup_time] => 1.6E-5
    [connect_time] => 0
    [pretransfer_time] => 5.5E-5
    [size_upload] => 44
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 9501
    [download_content_length] => 0
    [upload_content_length] => 44
    [starttransfer_time] => 0.004622
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 192.168.10.1
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 192.168.10.251
    [local_port] => 49571
    [http_version] => 2
    [protocol] => 2
    [ssl_verifyresult] => 0
    [scheme] => https
    [appconnect_time_us] => 0
    [connect_time_us] => 0
    [namelookup_time_us] => 16
    [pretransfer_time_us] => 55
    [redirect_time_us] => 0
    [starttransfer_time_us] => 4622
    [total_time_us] => 4631
    [effective_method] => POST
    [capath] => 
    [cainfo] => 
)

----------RESPONSE-----------

-----------------------------
</pre>
PHP Notice:  HTTP response status received: 404. Probably a controller login failure in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php on line 208

Notice: HTTP response status received: 404. Probably a controller login failure in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php on line 208
PHP Fatal error:  Uncaught TypeError: UniFi_API\Client::create_voucher(): Return value must be of type array, false returned in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php:2113
Stack trace:
#0 /Users/baumanisk/Development/source/git/UniFi-API-client/create_voucher.php(52): UniFi_API\Client->create_voucher(2000, 1)
#1 {main}
  thrown in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php on line 2113

Fatal error: Uncaught TypeError: UniFi_API\Client::create_voucher(): Return value must be of type array, false returned in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php:2113
Stack trace:
#0 /Users/baumanisk/Development/source/git/UniFi-API-client/create_voucher.php(52): UniFi_API\Client->create_voucher(2000, 1)
#1 {main}
  thrown in /Users/baumanisk/Development/source/git/UniFi-API-client/src/Client.php on line 2113

Process finished with exit code 255

```

**Comment by KarlBaumann** [comment]
I figured it out - the HTTPS just does not work, need to use HTTP instead

**Comment by malle-pietje** [comment]
Also: looks as if this is a UniFi OS console (UDM PRO or the likes) where you need to use port **443** in the URL, not 8443.
